server:
  port: 8080
spring:
  application:
    name: "customer"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://data_bd:5432/bank?currentSchema=public"
    username: "admin"
    password: "1234"
    driverClassName: "org.postgresql.Driver"
    logging:
      level:
        org.springframework.web: DEBUGrec
  jpa:
    #properties:
    #hibernate:
    #dialect: "com.test.CustomPostgreSQLDialect"
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  db:
    manangment:
      url: jdbc:postgresql://data_bd:5432/public
      host: data_bd
      bdname: bank
      port: 5432
      username: admin
      password: 1234
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
